name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: '${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: false
          command: |
            cd htdocs/pivovargaraz.cz/
            git pull
